export const COLLECTIONS = {
  ANNOUNCEMENTS: 'announcements',
  USERS: 'users',
  FEES: 'fees',
  COURSES: 'courses',
  ATTENDANCE: 'attendance',
  EXAMS: 'exams',
  PLACEMENTS: 'placementStats',
  SUCCESS_STORIES: 'successStories',
  OPPORTUNITIES: 'opportunities',
  PROGRESS: 'user_progress',
} as const;

export const FEE_STATUS = {
  PAID: 'paid',
  PENDING: 'pending',
  OVERDUE: 'overdue',
} as const;

export const ADMIN_USER_ID = 'admin';

export const PRIORITY_LEVELS = {
  HIGH: 'high',
  MEDIUM: 'medium',
  LOW: 'low',
} as const;

export const PRIORITY_COLORS = {
  [PRIORITY_LEVELS.HIGH]: '#EF4444',
  [PRIORITY_LEVELS.MEDIUM]: '#F59E0B',
  [PRIORITY_LEVELS.LOW]: '#10B981',
  DEFAULT: '#6B7280',
} as const;

export const DEFAULT_VALUES = {
  AUTHOR_ADMIN: 'Admin',
  TARGET_BATCH_ALL: 'All',
  ADMIN_WELCOME: 'Welcome back, Admin',
  ANALYTICS_OVERVIEW: 'Analytics Overview',
  DASHBOARD_SUBTEXT: 'Monitor platform performance at a glance.',
  ENGAGEMENT_TEXT: 'Engagement is up 12.5% compared to last month.',
  GROWTH_INSIGHTS: 'Growth Insights',
} as const;

export const DASHBOARD_METRICS = {
  TOTAL_STUDENTS: 'Total Students',
  FEES_COLLECTED: 'Fees Collected',
  EXAMS_CONDUCTED: 'Exams Conducted',
  SUCCESS_PLACEMENTS: 'Success Placements',
  TREND_MONTHLY: '+12% this month',
  TREND_GROWTH: '+5.4% growth',
  TREND_EXAMS: 'Next: Monday',
  TREND_PLACEMENTS: '85% Success Rate',
} as const;

export const UI_STRINGS = {
  // Common strings
  COMMON: {
    LOADING: 'Loading...',
    ERROR_PRIMARY: 'Something went wrong. Please try again.',
    CANCEL: 'Cancel',
    SAVE: 'Save',
    DELETE: 'Delete',
    EDIT: 'Edit',
    PUBLISH: 'Publish',
    SEARCH_PLACEHOLDER: 'Search...',
    NO_DATA: 'No results found.',
  },
  // Announcements page
  ANNOUNCEMENTS: {
    TITLE: 'Announcements',
    SUBTITLE: 'Send updates and notifications to students',
    NEW_BTN: 'New Announcement',
    MODAL_TITLE: 'New Announcement',
    EDIT_MODAL_TITLE: 'Edit Announcement',
    LOADING: 'Loading announcements...',
    ERROR_LOAD: 'Failed to load announcements. Please try again later.',
    ERROR_CREATE: 'Failed to create announcement. Please try again.',
    ERROR_UPDATE: 'Failed to update announcement. Please try again.',
    ERROR_DELETE: 'Failed to delete announcement. Please try again.',
    EMPTY: 'No announcements found.',
    FORM_TITLE: 'Title',
    FORM_CONTENT: 'Content',
    FORM_PRIORITY: 'Priority',
    TARGET_LABEL: 'Target',
    CONFIRM_DELETE_TITLE: 'Delete Announcement',
    CONFIRM_DELETE_DESC: 'Are you sure you want to delete this announcement? This action cannot be undone.',
    PREVIEW_TITLE: 'Mobile Preview',
    LIVE_PREVIEW: 'Live Preview',
  },
  // Courses page
  COURSES: {
    TITLE: 'Course Management',
    SUBTITLE: 'Manage courses, curriculum, and instructors',
    NEW_BTN: 'Add Course',
    MODAL_TITLE: 'Add New Course',
    LOADING: 'Loading courses...',
    ERROR_LOAD: 'Failed to load courses. Please try again later.',
    ERROR_CREATE: 'Failed to add course. Please try again.',
    FORM_TITLE: 'Course Title',
    FORM_TITLE_PLACEHOLDER: 'e.g. Full Stack Web Development',
    FORM_DESCRIPTION: 'Description',
    FORM_INSTRUCTOR: 'Instructor',
    FORM_DURATION: 'Duration',
    FORM_DURATION_PLACEHOLDER: 'e.g. 12 Weeks',
    FORM_PRICE: 'Price (₹)',
    FORM_FREE_COURSE: 'Free Course',
    FORM_THUMBNAIL_URL: 'Thumbnail URL (Optional)',
    BADGE_FREE: 'FREE',
  },
  // Users/Students page
  USERS: {
    TITLE: 'Students',
    SUBTITLE: 'Manage student profiles and enrollments',
    NEW_BTN: 'Add Student',
    MODAL_TITLE: 'Add New Student',
    LOADING: 'Loading students...',
    ERROR_LOAD: 'Failed to load students. Please try again later.',
    ERROR_CREATE: 'Failed to add student. Please try again.',
    EMPTY: 'No students found.',
    SEARCH: 'Search by name or email...',
    SELECT_COURSE: 'Select Course',
    SELECT_COURSE_PLACEHOLDER: '-- Choose a course --',
    // Table headers
    TH_NAME: 'Name',
    TH_BATCH: 'Batch',
    TH_COURSE: 'Course',
    TH_JOINED: 'Joined',
    TH_ACTIONS: 'Actions',
    // Form labels
    FORM_FULL_NAME: 'Full Name',
    FORM_EMAIL: 'Email',
    FORM_PHONE: 'Phone',
    FORM_BATCH: 'Batch',
    FORM_BATCH_PLACEHOLDER: 'e.g. 2024-A',

    // View details
    VIEW_DETAILS: 'View Full Details',
    CLOSE_DETAILS: 'Close Details',
    CONTACT_INFO: 'Contact Information',
    ACADEMIC_DETAILS: 'Academic Details',
    ENROLLED_COURSES: 'Enrolled Courses',
    EMAIL_LABEL: 'Email:',
    PHONE_LABEL: 'Phone:',
    ENROLLMENT_DATE_LABEL: 'Enrollment Date:',
    CURRENT_STATUS_LABEL: 'Current Status:',
    STATUS_ACTIVE: 'Active',
    NOT_PROVIDED: 'Not provided',
  },
  // Exams page
  EXAMS: {
    TITLE: 'Examinations',
    SUBTITLE: 'Create and manage student assessments',
    NEW_BTN: 'Create New Exam',
    MODAL_TITLE: 'Create New Assessment',
    LOADING: 'Loading exams...',
    ERROR_LOAD: 'Failed to load exams. Please try again later.',
    ERROR_CREATE: 'Failed to create exam. Please try again.',
    EMPTY: 'No exams found matching your search.',
    SEARCH_PLACEHOLDER: 'Search by title or category...',
    FORM_TITLE: 'Exam Title',
    FORM_TITLE_PLACEHOLDER: 'e.g. Mid-term React Assessment',
    FORM_DESCRIPTION: 'Description',
    FORM_CATEGORY: 'Category',
    FORM_CATEGORY_PLACEHOLDER: 'e.g. Web Development',
    FORM_DIFFICULTY: 'Difficulty',
    FORM_DURATION: 'Duration (mins)',
    FORM_TOTAL_MARKS: 'Total Marks',
    FORM_SCHEDULED_DATE: 'Scheduled Date',
    DIFFICULTY_EASY: 'Easy',
    DIFFICULTY_MEDIUM: 'Medium',
    DIFFICULTY_HARD: 'Hard',
    QUESTIONS_SUFFIX: 'Questions',
    MARKS_SUFFIX: 'Marks',
    MINS_SUFFIX: 'mins',
  },
  FEES: {
    TITLE: 'Student Fee Status',
    SUBTITLE: 'Monitor payment status across all enrolled students',
    LOADING: 'Loading fee records...',
    NEW_BTN: 'New Fee Record',
    SEARCH: 'Search by student or course...',
    EMPTY: 'No student summaries found.',
    MODAL_TITLE: 'Create Fee Record',
    ERROR_LOAD: 'Failed to load fee information. Please try again later.',
    ERROR_UPDATE: 'Failed to update payment status.',
    ERROR_CREATE: 'Failed to create fee record.',
    // Table headers
    TH_STUDENT: 'Student',
    TH_COURSE: 'Course',
    TH_TOTAL_FEE: 'Total Fee',
    TH_PAID: 'Paid',
    TH_PENDING: 'Pending',
    TH_STATUS: 'Status',
    TH_ACTIONS: 'Actions',
    // Stat labels
    STAT_COLLECTED: 'Total Collected',
    STAT_PENDING: 'Pending',
    STAT_OVERDUE: 'Overdue',
    // Form labels
    FORM_SELECT_STUDENT: 'Student',
    FORM_SELECT_STUDENT_PLACEHOLDER: 'Select Student',
    FORM_AMOUNT: 'Amount (₹)',
    FORM_DUE_DATE: 'Due Date',
    FORM_DESCRIPTION: 'Description',
    FORM_DESCRIPTION_PLACEHOLDER: 'e.g. Monthly Tuition Fee - March',
    FORM_STATUS: 'Status',
    STATUS_PENDING: 'Pending',
    STATUS_PAID: 'Paid',
    STATUS_OVERDUE: 'Overdue',
    // Detail modal
    DETAILS_BTN: 'Details',
    TRANSACTION_HISTORY: 'Transaction History',
    TOTAL_PAID: 'Total Paid',
    BALANCE_DUE: 'Balance Due',
    MARK_PAID: 'Mark Paid',
    PAID_CONFIRMED: 'Paid',
    // Detail modal table headers
    TH_DETAIL_DESCRIPTION: 'Description',
    TH_DETAIL_AMOUNT: 'Amount',
    TH_DETAIL_DUE_DATE: 'Due Date',
    TH_DETAIL_STATUS: 'Status',
    TH_DETAIL_ACTION: 'Action',
    // Status values
    ALL_CLEAR: 'All Clear',
    NO_RECORDS: 'No Records',
  },
  PLACEMENTS: {
    TITLE: 'Success Stories',
    SUBTITLE: 'Track student placement records and success stories',
    LOADING: 'Loading placements...',
    NEW_BTN: 'Add Success Story',
    ERROR_LOAD: 'Failed to load placement records. Please try again later.',
    ERROR_SAVE: 'Failed to save success story.',
    MODAL_TITLE: 'Add Success Story',
    // Stat labels
    STAT_PARTNER_COMPANIES: 'Partner Companies',
    STAT_PLACED_STUDENTS: 'Placed Students',
    STAT_HIGHEST_PACKAGE: 'Highest Package',
    SUCCESS_STORIES_HEADING: 'Success Stories',
    LPA_SUFFIX: 'LPA',
    // Form labels
    FORM_STUDENT_NAME: 'Student Name',
    FORM_COMPANY: 'Company',
    FORM_COMPANY_PLACEHOLDER: 'e.g. Google',
    FORM_PACKAGE: 'Package',
    FORM_PACKAGE_PLACEHOLDER: 'e.g. 12 LPA',
    FORM_ROLE: 'Role',
    FORM_ROLE_PLACEHOLDER: 'e.g. Software Engineer',
    FORM_BATCH: 'Batch',
    FORM_BATCH_PLACEHOLDER: 'e.g. 2024',
    FORM_TESTIMONIAL: 'Testimonial (Optional)',
    FORM_IMAGE_URL: 'Upload Photo (PNG/JPG)',
    // Card display
    ROLE_PREFIX: 'Role:',
    BATCH_PREFIX: 'Batch:',
    PACKAGE_PREFIX: 'Package:',
  },
  NAV: {
    DASHBOARD: 'Dashboard',
    STUDENTS: 'Students',
    FEES: 'Fees',
    EXAMS: 'Exams',
    PLACEMENTS: 'Success Stories',
    COURSES: 'Courses',
    PROGRESS: 'Progress',
    ANNOUNCEMENTS: 'Announcements',
    LOGOUT: 'Logout',
    ADMIN: 'Admin',
  },
  PROGRESS: {
    TITLE: 'Student Progress',
    SUBTITLE: 'Monitor academic performance and attendance across all batches',
    LOADING: 'Loading progress data...',
    EMPTY: 'No progress records found. Update student performance to see data here.',
    VIEW_REPORT: 'View Full Report',
    MODULES_COMPLETED: 'Modules Completed',
    UNKNOWN_STUDENT: 'Unknown Student',
  },
  LOGIN: {
    TITLE: 'Admin Portal',
    SUBTITLE: 'Sign in to manage your institution',
    EMAIL_LABEL: 'Email Address',
    PASSWORD_LABEL: 'Password',
    BTN: 'Sign In',
    ERROR: 'Invalid email or password.',
    LOADING: 'Signing in...',
    FEATURES: {
      COURSES_TITLE: 'Verified Courses',
      COURSES_DESC: 'Expert-led curriculum for modern skills.',
      TRACKING_TITLE: 'Smart Tracking',
      TRACKING_DESC: 'Real-time progress and performance analytics.',
      MENTORSHIP_TITLE: 'Expert Mentorship',
      MENTORSHIP_DESC: 'Direct guidance from industry veterans.',
    },
    FOOTER_SUPPORT: 'Need technical support?',
    FOOTER_CONTACT: 'Contact Systems',
    BRANDING_TEXT: 'Empowering the',
    BRANDING_HIGHLIGHT: 'Future',
    BRANDING_SUFFIX: 'of Digital Learning & Management.',
    EMAIL_PLACEHOLDER: 'Enter email address',
    PASSWORD_PLACEHOLDER: '••••••••',
  },
  THEME: {
    SWITCH_DARK: 'Switch to Dark Mode',
    SWITCH_LIGHT: 'Switch to Light Mode',
  }
} as const;
