export const COLLECTIONS = {
  ANNOUNCEMENTS: 'announcements',
  USERS: 'users',
  FEES: 'fees',
  PAYMENT_HISTORY: 'paymentHistory',
  COURSES: 'courses',
  ATTENDANCE: 'attendance',
  EXAMS: 'exams',
  PLACEMENTS: 'placements',
  PLACEMENT_STATS: 'placementStats',
  OPPORTUNITIES: 'opportunities',
  PROGRESS: 'user_progress',
  EXAM_RESULTS: 'examResults',
  JOBS: 'jobs',
  DEVICES: 'devices',
  NOTIFICATIONS: 'notifications',
  BATCHES: 'batches',
  ENROLLMENT_REQUESTS: 'enrollment_requests',
  PLACEMENT_TALLY: 'placementTally',
  MOCK_SCHEDULES: 'mockSchedules',
} as const;

export const FEE_STATUS = {
  PAID: 'paid',
  PENDING: 'pending',
  OVERDUE: 'overdue',
  PARTIAL: 'partial',
} as const;

export const PAYMENT_METHODS = [
  { id: 'Cash', label: 'Cash' },
  { id: 'Bank', label: 'Bank Transfer' },
  { id: 'Manual', label: 'Manual Entry' },
] as const;

export const ATTENDANCE_STATUS = {
  PRESENT: 'present',
  ABSENT: 'absent',
  LATE: 'late',
  EXCUSED: 'excused',
} as const;

export const ADMIN_USER_ID = 'admin';

export const PRIORITY_LEVELS = {
  HIGH: 'high',
  MEDIUM: 'medium',
  LOW: 'low',
} as const;

export const PRIORITY_COLORS = {
  [PRIORITY_LEVELS.HIGH]: '#EF4444',
  [PRIORITY_LEVELS.MEDIUM]: '#F59E0B',
  [PRIORITY_LEVELS.LOW]: '#10B981',
  DEFAULT: '#6B7280',
} as const;

export const DEFAULT_VALUES = {
  AUTHOR_ADMIN: 'Admin',
  TARGET_BATCH_ALL: 'All',
  ADMIN_WELCOME: 'Welcome back, Admin',
  ANALYTICS_OVERVIEW: 'Analytics Overview',
  DASHBOARD_SUBTEXT: 'Monitor platform performance at a glance.',
  ENGAGEMENT_TEXT: 'Engagement is up 12.5% compared to last month.',
  GROWTH_INSIGHTS: 'Growth Insights',
} as const;

export const DASHBOARD_METRICS = {
  TOTAL_STUDENTS: 'Total Students',
  FEES_COLLECTED: 'Fees Collected',
  EXAMS_CONDUCTED: 'Exams Conducted',
  SUCCESS_PLACEMENTS: 'Success Placements',
} as const;

export const UI_STRINGS = {
  // Common strings
  COMMON: {
    LOADING: 'Loading...',
    ERROR_PRIMARY: 'Something went wrong. Please try again.',
    CANCEL: 'Cancel',
    SAVE: 'Save',
    DELETE: 'Delete',
    EDIT: 'Edit',
    PUBLISH: 'Publish',
    SEARCH_PLACEHOLDER: 'Search...',
    NO_DATA: 'No results found.',
    N_A: 'N/A'
  },
  // Announcements page
  ANNOUNCEMENTS: {
    TITLE: 'Announcements',
    SUBTITLE: 'Send updates and notifications to students',
    NEW_BTN: 'New Announcement',
    MODAL_TITLE: 'New Announcement',
    EDIT_MODAL_TITLE: 'Edit Announcement',
    LOADING: 'Loading announcements...',
    ERROR_LOAD: 'Failed to load announcements. Please try again later.',
    ERROR_CREATE: 'Failed to create announcement. Please try again.',
    ERROR_UPDATE: 'Failed to update announcement. Please try again.',
    ERROR_DELETE: 'Failed to delete announcement. Please try again.',
    EMPTY: 'No announcements found.',
    FORM_TITLE: 'Title',
    FORM_CONTENT: 'Content',
    FORM_PRIORITY: 'Priority',
    TARGET_LABEL: 'Target',
    TARGET_ALL: 'All Students',
    TARGET_BATCH: 'Specific Batches',
    TARGET_STUDENTS: 'Specific Students',
    STUDENT_SEARCH_PLACEHOLDER: 'Search students by name or email...',
    CONFIRM_DELETE_TITLE: 'Delete Announcement',
    CONFIRM_DELETE_DESC: 'Are you sure you want to delete this announcement? This action cannot be undone.',
    PREVIEW_TITLE: 'Mobile Preview',
    LIVE_PREVIEW: 'Live Preview',
    FORM_POPUP: 'Popup Banner',
    FORM_POPUP_DESC: 'Show as popup on student\'s home screen',
    FORM_POPUP_HINT: 'When checked, this announcement will slide up as a banner when students open the app.',
  },
  // Courses page
  COURSES: {
    TITLE: 'Course Management',
    SUBTITLE: 'Manage courses, curriculum, and instructors',
    NEW_BTN: 'Add Course',
    MODAL_TITLE: 'Add New Course',
    LOADING: 'Loading courses...',
    ERROR_LOAD: 'Failed to load courses. Please try again later.',
    ERROR_CREATE: 'Failed to add course. Please try again.',
    FORM_TITLE: 'Course Title',
    FORM_TITLE_PLACEHOLDER: 'e.g. Full Stack Web Development',
    FORM_DESCRIPTION: 'Description',
    FORM_INSTRUCTOR: 'Instructor',
    FORM_DURATION: 'Duration',
    FORM_DURATION_PLACEHOLDER: 'e.g. 12 Weeks',
    FORM_PRICE: 'Price (₹)',
    FORM_FREE_COURSE: 'Free Course',
    FORM_THUMBNAIL_URL: 'Thumbnail URL (Optional)',
    BADGE_FREE: 'FREE',
  },
  // Users/Students page
  USERS: {
    TITLE: 'Students',
    SUBTITLE: 'Manage student profiles and enrollments',
    NEW_BTN: 'Add Student',
    MODAL_TITLE: 'Add New Student',
    LOADING: 'Loading students...',
    ERROR_LOAD: 'Failed to load students. Please try again later.',
    ERROR_CREATE: 'Failed to add student. Please try again.',
    EMPTY: 'No students found.',
    SEARCH: 'Search by name or email...',
    SELECT_COURSE: 'Select Course',
    SELECT_COURSE_PLACEHOLDER: '-- Choose a course --',
    // Table headers
    TH_NAME: 'Name',
    TH_BATCH: 'Batch',
    TH_COURSE: 'Course',
    TH_JOINED: 'Joined',
    TH_ACTIONS: 'Actions',
    // Form labels
    FORM_FULL_NAME: 'Full Name',
    FORM_EMAIL: 'Email',
    FORM_PHONE: 'Phone',
    FORM_BATCH: 'Batch',
    FORM_BATCH_PLACEHOLDER: 'e.g. 2024-A',

    // View details
    VIEW_DETAILS: 'View Full Details',
    CLOSE_DETAILS: 'Close Details',
    CONTACT_INFO: 'Contact Information',
    ACADEMIC_DETAILS: 'Academic Details',
    ENROLLED_COURSES: 'Enrolled Courses',
    EMAIL_LABEL: 'Email:',
    PHONE_LABEL: 'Phone:',
    ENROLLMENT_DATE_LABEL: 'Enrollment Date:',
    CURRENT_STATUS_LABEL: 'Current Status:',
    STATUS_ACTIVE: 'Active',
    NOT_PROVIDED: 'Not provided',
    // Block/Unblock
    TAB_ACTIVE: 'Active Students',
    TAB_BLOCKED: 'Blocked Students',
    BLOCK_CONFIRM_TITLE: 'Block Student',
    BLOCK_CONFIRM_MSG: 'Are you sure you want to block this student? They will be immediately logged out and unable to access the platform.',
    BLOCK_REASON_LABEL: 'Block Reason (Optional)',
    BLOCK_REASON_PLACEHOLDER: 'e.g. Violation of terms, Non-payment, etc.',
    BLOCK_SUCCESS: 'Student blocked successfully',
    UNBLOCK_CONFIRM_TITLE: 'Unblock Student',
    UNBLOCK_CONFIRM_MSG: 'Are you sure you want to unblock this student? They will regain full access to the platform.',
    UNBLOCK_SUCCESS: 'Student unblocked successfully',
    BLOCKED_EMPTY: 'No blocked students found.',
    BLOCKED_DATE: 'Blocked Date',
    BLOCKED_REASON: 'Reason',
    BLOCK_ERROR: 'Failed to update block status',
  },
  // Exams page
  EXAMS: {
    TITLE: 'Examinations',
    SUBTITLE: 'Create and manage student assessments',
    NEW_BTN: 'Create New Exam',
    MODAL_TITLE: 'Create New Assessment',
    LOADING: 'Loading exams...',
    ERROR_LOAD: 'Failed to load exams. Please try again later.',
    ERROR_CREATE: 'Failed to create exam. Please try again.',
    EMPTY: 'No exams found matching your search.',
    SEARCH_PLACEHOLDER: 'Search by title or category...',
    FORM_TITLE: 'Exam Title',
    FORM_TITLE_PLACEHOLDER: 'e.g. Mid-term React Assessment',
    FORM_DESCRIPTION: 'Description',
    FORM_CATEGORY: 'Category',
    FORM_CATEGORY_PLACEHOLDER: 'e.g. Web Development',
    FORM_DIFFICULTY: 'Difficulty',
    FORM_DURATION: 'Duration (mins)',
    FORM_TOTAL_MARKS: 'Total Marks',
    FORM_SCHEDULED_DATE: 'Scheduled Date',
    DIFFICULTY_EASY: 'Easy',
    DIFFICULTY_MEDIUM: 'Medium',
    DIFFICULTY_HARD: 'Hard',
    QUESTIONS_SUFFIX: 'Questions',
    MARKS_SUFFIX: 'Marks',
    MINS_SUFFIX: 'mins',
  },
  FEES: {
    TITLE: 'Student Fee Status',
    SUBTITLE: 'Monitor payment status across all enrolled students',
    LOADING: 'Loading fee records...',
    NEW_BTN: 'New Fee Record',
    SEARCH: 'Search by student or course...',
    EMPTY: 'No student summaries found.',
    MODAL_TITLE: 'Create Fee Record',
    ERROR_LOAD: 'Failed to load fee information. Please try again later.',
    ERROR_UPDATE: 'Failed to update payment status.',
    ERROR_CREATE: 'Failed to create fee record.',
    // Table headers
    TH_STUDENT: 'Student',
    TH_COURSE: 'Course',
    TH_TOTAL_FEE: 'Total Fee',
    TH_PAID: 'Paid',
    TH_PENDING: 'Pending',
    TH_STATUS: 'Status',
    TH_ACTIONS: 'Actions',
    // Stat labels
    STAT_COLLECTED: 'Total Collected',
    STAT_PENDING: 'Pending',
    STAT_OVERDUE: 'Overdue',
    // Form labels
    FORM_SELECT_STUDENT: 'Student',
    FORM_SELECT_STUDENT_PLACEHOLDER: 'Select Student',
    FORM_AMOUNT: 'Amount (₹)',
    FORM_DUE_DATE: 'Due Date',
    FORM_DESCRIPTION: 'Description',
    FORM_DESCRIPTION_PLACEHOLDER: 'e.g. Monthly Tuition Fee - March',
    FORM_STATUS: 'Status',
    STATUS_PENDING: 'Pending',
    STATUS_PAID: 'Paid',
    STATUS_OVERDUE: 'Overdue',
    // Detail modal
    DETAILS_BTN: 'Details',
    TRANSACTION_HISTORY: 'Transaction History',
    TOTAL_PAID: 'Total Paid',
    BALANCE_DUE: 'Balance Due',
    MARK_PAID: 'Mark Paid',
    PAID_CONFIRMED: 'Paid',
    // Detail modal table headers
    TH_DETAIL_DESCRIPTION: 'Description',
    TH_DETAIL_AMOUNT: 'Amount',
    TH_DETAIL_DUE_DATE: 'Due Date',
    TH_DETAIL_STATUS: 'Status',
    TH_DETAIL_ACTION: 'Action',
    // Installment strings
    ADD_INSTALLMENT: 'Add Installment',
    INSTALLMENT_HISTORY: 'Installment History',
    INSTALLMENT_AMOUNT: 'Amount (₹)',
    INSTALLMENT_METHOD: 'Payment Method',
    INSTALLMENT_DATE: 'Payment Date',
    INSTALLMENT_NOTES: 'Notes (Optional)',
    INSTALLMENT_EMPTY: 'No installments recorded yet.',
    // Status values
    ALL_CLEAR: 'All Clear',
    STATUS_PARTIAL: 'Partial',
    NO_RECORDS: 'No Records',
  },
  ATTENDANCE: {
    TITLE: 'Attendance',
    SUBTITLE: 'Track and manage daily class attendance',
    LOADING: 'Loading attendance...',
    ERROR_LOAD: 'Failed to load attendance records.',
    ERROR_SAVE: 'Failed to save attendance.',
    SUCCESS_SAVE: 'Attendance saved successfully.',
    MARK_ATTENDANCE: 'Mark Attendance',
    CALENDAR_VIEW: 'Calendar View',
    REPORTS: 'Reports',
    SELECT_COURSE: 'Select Course',
    SELECT_BATCH: 'Select Batch',
    SELECT_DATE: 'Select Date',
    MARK_ALL_PRESENT: 'Mark All Present',
    MARK_ALL_ABSENT: 'Mark All Absent',
    SUBMIT: 'Submit Attendance',
    TH_STUDENT: 'Student',
    TH_STATUS: 'Status',
    TH_BATCH: 'Batch',
    TH_PRESENT: 'Present',
    TH_ABSENT: 'Absent',
    TH_LATE: 'Late',
    TH_EXCUSED: 'Excused',
    TH_PERCENTAGE: '%',
    EMPTY: 'No students found for this selection.',
    EMPTY_CALENDAR: 'No attendance records found for this month.',
    STAT_COURSE_AVG: 'Course Average',
    STAT_STUDENTS: 'Total Students',
  },
  PLACEMENTS: {
    TITLE: 'Success Stories',
    SUBTITLE: 'Track student placement records and success stories',
    LOADING: 'Loading placements...',
    NEW_BTN: 'Add Success Story',
    ERROR_LOAD: 'Failed to load placement records. Please try again later.',
    ERROR_SAVE: 'Failed to save success story.',
    MODAL_TITLE: 'Add Success Story',
    // Stat labels
    STAT_PARTNER_COMPANIES: 'Partner Companies',
    STAT_PLACED_STUDENTS: 'Placed Students',
    STAT_HIGHEST_PACKAGE: 'Highest Package',
    SUCCESS_STORIES_HEADING: 'Success Stories',
    LPA_SUFFIX: 'LPA',
    // Form labels
    FORM_STUDENT_NAME: 'Student Name',
    FORM_COMPANY: 'Company',
    FORM_COMPANY_PLACEHOLDER: 'e.g. Google',
    FORM_PACKAGE: 'Package',
    FORM_PACKAGE_PLACEHOLDER: 'e.g. 12 LPA',
    FORM_STREAM: 'Stream',
    FORM_STREAM_PLACEHOLDER: 'e.g. Stream',
    FORM_ROLE: 'Role',
    FORM_ROLE_PLACEHOLDER: 'e.g. Software Engineer',
    FORM_BATCH: 'Batch',
    FORM_BATCH_PLACEHOLDER: 'e.g. 2024',
    FORM_IMAGE_URL: 'Upload Photo (PNG/JPG)',
    // Card display
    ROLE_PREFIX: 'Role:',
    BATCH_PREFIX: 'Batch:',
    PACKAGE_PREFIX: 'Package:',
    // Year-wise and Stats management
    SELECT_YEAR: 'Select Year',
    EDIT_STATS: 'Edit Yearly Stats',
    DELETE_STORY_CONFIRM: 'Are you sure you want to delete this success story?',
    DELETE_STORY_SUCCESS: 'Success story deleted successfully.',
    SAVE_STATS_SUCCESS: 'Placement statistics updated successfully.',
    FORM_YEAR: 'Placement Year',
    FORM_COMPANIES_COUNT: 'Total Companies',
    FORM_STUDENTS_PLACED: 'Students Placed',
    FORM_AVG_PACKAGE: 'Average Package (LPA)',
    FORM_HIGHEST_PACKAGE: 'Highest Package (LPA)',
  },
  JOBS: {
    TITLE: 'Job Management',
    SUBTITLE: 'Manage job postings and track applicants',
    LOADING: 'Loading jobs...',
    NEW_BTN: 'Post New Job',
    MODAL_TITLE: 'Post New Job',
    EDIT_MODAL_TITLE: 'Edit Job',
    ERROR_LOAD: 'Failed to load jobs.',
    ERROR_SAVE: 'Failed to save job.',
    ERROR_DELETE: 'Failed to delete job.',
    EMPTY: 'No jobs found.',
    DELETE_CONFIRM: 'Are you sure you want to delete this job posting?',
    DELETE_SUCCESS: 'Job deleted successfully.',
    SAVE_SUCCESS: 'Job saved successfully.',
    STATUS_UPDATE_SUCCESS: 'Application status updated.',
    // Filters
    FILTER_ALL: 'All Types',
    FILTER_FULLTIME: 'Full-time',
    FILTER_INTERNSHIP: 'Internship',
    SEARCH_PLACEHOLDER: 'Search by company or role...',
    // Form labels
    FORM_COMPANY: 'Company Name',
    FORM_COMPANY_PLACEHOLDER: 'e.g. Google',
    FORM_ROLE: 'Role',
    FORM_ROLE_PLACEHOLDER: 'e.g. Software Engineer',
    FORM_LOCATION: 'Location',
    FORM_LOCATION_PLACEHOLDER: 'e.g. Bangalore, India',
    FORM_SALARY: 'Salary',
    FORM_SALARY_PLACEHOLDER: 'e.g. 8-12 LPA',
    FORM_JOB_TYPE: 'Job Type',
    FORM_REQUIREMENTS: 'Requirements (one per line)',
    FORM_REQUIREMENTS_PLACEHOLDER: 'React.js\nNode.js\nTypeScript',
    FORM_DESCRIPTION: 'Description (Optional)',
    FORM_ELIGIBLE_BATCHES: 'Eligible Batches (comma-separated, leave empty for all)',
    FORM_ELIGIBLE_BATCHES_PLACEHOLDER: 'e.g. 2024-A, 2025-B',
    FORM_APPLY_LINK: 'External Apply Link (Optional)',
    FORM_APPLY_LINK_PLACEHOLDER: 'https://careers.company.com/apply',
    FORM_DEADLINE: 'Application Deadline (Optional)',
    FORM_IS_ACTIVE: 'Active',
    // Table headers
    TH_COMPANY: 'Company',
    TH_ROLE: 'Role',
    TH_LOCATION: 'Location',
    TH_SALARY: 'Salary',
    TH_TYPE: 'Type',
    TH_POSTED: 'Posted',
    TH_ACTIONS: 'Actions',
    // Applicant tracking
    APPLICANTS_TITLE: 'Applicants',
    APPLICANTS_EMPTY: 'No applicants yet.',
    TH_APPLICANT: 'Applicant',
    TH_BATCH: 'Batch',
    TH_STATUS: 'Status',
    TH_APPLIED_DATE: 'Applied Date',
    BACK_TO_JOBS: '← Back to Jobs',
    // Stat labels
    STAT_TOTAL_JOBS: 'Total Jobs',
    STAT_ACTIVE_JOBS: 'Active Jobs',
    STAT_TOTAL_APPLICANTS: 'Total Applicants',
  },
  NAV: {
    DASHBOARD: 'Dashboard',
    STUDENTS: 'Students',
    FEES: 'Fees',
    ATTENDANCE: 'Attendance',
    EXAMS: 'Exams',
    PLACEMENTS: 'Success Stories',
    JOBS: 'Job Management',
    COURSES: 'Courses',
    PROGRESS: 'Progress',
    ANNOUNCEMENTS: 'Announcements',
    NOTIFICATIONS: 'Notifications',
    BATCHES: 'Batches',
    MOCK_SCHEDULING: 'Mock Scheduling',
    LOGOUT: 'Logout',
    ADMIN: 'Admin Portal',
  },
  NOTIFICATIONS: {
    TITLE: 'Push Notifications',
    SUBTITLE: 'Send push notifications to students',
    LOADING: 'Loading notifications...',
    SEND_BTN: 'Send Notification',
    FORM_TITLE: 'Title',
    FORM_TITLE_PLACEHOLDER: 'e.g. Class cancelled tomorrow',
    FORM_BODY: 'Message',
    FORM_BODY_PLACEHOLDER: 'Enter notification message...',
    TARGET_LABEL: 'Target Audience',
    TARGET_ALL: 'All Students',
    TARGET_BATCH: 'Specific Batches',
    TARGET_STUDENTS: 'Specific Students',
    STUDENT_SEARCH_PLACEHOLDER: 'Search students by name or email...',
    HISTORY_TITLE: 'Notification History',
    HISTORY_EMPTY: 'No notifications sent yet.',
    SENDING: 'Sending...',
    SUCCESS: 'Notification sent successfully!',
    ERROR_SEND: 'Failed to send notification. Please try again.',
    ERROR_LOAD: 'Failed to load notification history.',
    TH_TITLE: 'Title',
    TH_TARGET: 'Target',
    TH_DEVICES: 'Devices',
    TH_SENT_AT: 'Sent At',
  },
  EXAM_RESULTS: {
    TITLE: 'Exam Results',
    SUBTITLE: 'Analyze student performance and scores across all exams',
    LOADING: 'Loading exam results...',
    EMPTY_EXAM: 'No results found for this exam.',
    EMPTY_STUDENT: 'No exams attempted by this student yet.',
    EXPORT_CSV: 'Export CSV',
    SEARCH_PLACEHOLDER: 'Search students by name or email...',
    TAB_BY_EXAM: 'By Exam',
    TAB_BY_STUDENT: 'By Student',
    SELECT_EXAM: 'Select Exam',
    SELECT_EXAM_PLACEHOLDER: '-- Choose an exam --',
    PASS_THRESHOLD: 'Pass Threshold',
    PASS_THRESHOLD_DESC: 'Adjust to see pass/fail ratio',
    // Stat cards
    STAT_TOTAL_ATTEMPTS: 'Total Attempts',
    STAT_AVG_SCORE: 'Average Score',
    STAT_PASS_RATE: 'Pass Rate',
    STAT_TOP_SCORE: 'Top Score',
    // Charts
    CHART_SCORE_DISTRIBUTION: 'Score Distribution',
    CHART_PASS_FAIL: 'Pass vs Fail',
    PASSED: 'Passed',
    FAILED: 'Failed',
    // Table
    TH_STUDENT: 'Student',
    TH_EXAM: 'Exam',
    TH_SCORE: 'Score',
    TH_PERCENTAGE: 'Percentage',
    TH_TIME_TAKEN: 'Time Taken',
    TH_STATUS: 'Status',
    TH_DATE: 'Date',
  },
  PROGRESS: {
    TITLE: 'Student Progress',
    SUBTITLE: 'Monitor academic performance and attendance across all batches',
    LOADING: 'Loading progress data...',
    EMPTY: 'No progress records found. Update student performance to see data here.',
    VIEW_REPORT: 'View Full Report',
    MODULES_COMPLETED: 'Modules Completed',
    UNKNOWN_STUDENT: 'Unknown Student',
  },
  LOGIN: {
    TITLE: 'Admin Portal',
    SUBTITLE: 'Sign in to manage your institution',
    EMAIL_LABEL: 'Email Address',
    PASSWORD_LABEL: 'Password',
    BTN: 'Sign In',
    ERROR: 'Invalid email or password.',
    LOADING: 'Signing in...',
    FEATURES: {
      COURSES_TITLE: 'Verified Courses',
      COURSES_DESC: 'Expert-led curriculum for modern skills.',
      TRACKING_TITLE: 'Smart Tracking',
      TRACKING_DESC: 'Real-time progress and performance analytics.',
      MENTORSHIP_TITLE: 'Expert Mentorship',
      MENTORSHIP_DESC: 'Direct guidance from industry veterans.',
    },
    FOOTER_SUPPORT: 'Need technical support?',
    FOOTER_CONTACT: 'Contact Systems',
    BRANDING_TEXT: 'Empowering the',
    BRANDING_HIGHLIGHT: 'Future',
    BRANDING_SUFFIX: 'of Digital Learning & Management.',
    EMAIL_PLACEHOLDER: 'Enter email address',
    PASSWORD_PLACEHOLDER: '••••••••',
    FORGOT_PASSWORD_LINK: 'Forgot Password?',
    FORGOT_PASSWORD_TITLE: 'Reset Password',
    FORGOT_PASSWORD_SUBTITLE: 'Enter your admin email to receive a password reset link.',
    FORGOT_PASSWORD_SUCCESS: 'Password reset email sent! Please check your inbox.',
    FORGOT_PASSWORD_ERROR: 'Failed to send reset email. Please verify your email or try again.',
    SEND_RESET_LINK: 'Send Reset Link',
  },
  BATCHES: {
    TITLE: 'Batch Management',
    SUBTITLE: 'Create and manage student batches and enrollment requests',
    NEW_BTN: 'Create Batch',
    TAB_MANAGE: 'Manage Batches',
    TAB_REQUESTS: 'Enrollment Requests',
    MODAL_TITLE: 'Create New Batch',
    EDIT_MODAL_TITLE: 'Edit Batch',
    LOADING: 'Loading batches...',
    ERROR_LOAD: 'Failed to load batches.',
    ERROR_CREATE: 'Failed to create batch.',
    ERROR_UPDATE: 'Failed to update batch.',
    DELETE_CONFIRM: 'Are you sure you want to delete this batch?',
    EMPTY: 'No batches found.',
    FORM_NAME: 'Batch Name',
    FORM_NAME_PLACEHOLDER: 'e.g. 2024-A (Morning)',
    FORM_BATCH_CODE: 'Batch Code',
    FORM_BATCH_CODE_PLACEHOLDER: 'e.g. JAVA2024, ABC123',
    FORM_COURSE: 'Course',
    FORM_START_DATE: 'Start Date',
    FORM_END_DATE: 'End Date',
    FORM_ACTIVE: 'Active',
    FORM_DESCRIPTION: 'Description (Optional)',
    REQUESTS_EMPTY: 'No pending enrollment requests.',
    APPROVE: 'Approve',
    REJECT: 'Reject',
    APPROVE_SUCCESS: 'Student enrolled successfully.',
    REJECT_SUCCESS: 'Request rejected.',
    TH_STUDENT: 'Student',
    TH_BATCH: 'Batch',
    TH_COURSE: 'Course',
    TH_REQUESTED: 'Requested At',
    TH_ACTIONS: 'Actions',
  },
  THEME: {
    SWITCH_DARK: 'Switch to Dark Mode',
    SWITCH_LIGHT: 'Switch to Light Mode',
  },
  DEVICE_APPROVALS: {
    TITLE: 'Device Approvals',
    SUBTITLE: 'Approve or reject login requests from new devices',
    LOADING: 'Loading device requests...',
    EMPTY: 'No device requests found for this filter.',
    APPROVE_SUCCESS: 'Device approved successfully.',
    REJECT_SUCCESS: 'Device rejected successfully.',
    DELETE_SUCCESS: 'Device record removed.',
    ERROR_UPDATE: 'Failed to update device status.',
  },
  MOCK_SCHEDULING: {
    TITLE: 'Mock Schedules',
    SUBTITLE: 'Create mock schedules and view student self-registrations',
    LOADING: 'Loading schedules...',
    CREATE_BTN: 'Create Mock Schedule',
    NEW_SCHEDULE: 'New Mock Schedule',
    FORM_TITLE: 'Schedule Title',
    FORM_DATE: 'Schedule Date',
    FORM_LIMIT: 'Student Limit',
    FORM_LIMIT_DESC: 'Maximum number of students allowed to register',
    FORM_DESC: 'Description',
    ACTIVE_SCHEDULES: 'Active Schedules',
    NO_SCHEDULES: 'No mock schedules created yet.',
    REGISTRATIONS: 'Registrations',
    NO_REGISTRATIONS: 'No students registered yet for this schedule.',
    CLOSE_REGISTRATION: 'Close Registration',
    CLOSED: 'Closed',
    OPEN: 'Open',
    COMPLETED: 'Completed',
    LIMIT_REACHED: 'Limit Reached',
    ERROR_LOAD: 'Failed to load mock schedules.',
    ERROR_CREATE: 'Failed to create mock schedule.',
    SUCCESS_CREATE: 'Mock schedule created and notifications sent!',
    SUCCESS_CLOSE: 'Registration closed successfully.',
    CONFIRM_DELETE_TITLE: 'Delete Mock Schedule',
    CONFIRM_DELETE_DESC: 'Are you sure you want to delete this schedule and all its registrations? This cannot be undone.',
  },
} as const;
